version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api"
s3_bucket = "api.forcepu.sh"
s3_prefix = "api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
