AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31


Parameters:
  Domain:
    Type: "String"

Resources:
  HostedZone: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      Name: !Ref Domain