AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  forcepu.sh

  Sample SAM Template for forcepu.sh
Parameters:
  S3Bucket:
    Type: "String"
  AWSAccessKeyId:
    Type: "String"
  AWSSecretAccessKey:
    Type: "String"
  AWSDefaultRegion:
    Type: "String"
  Dev:
    Type: "String"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  ExerciseLogFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: backend/
      Handler: gym.get_exercise_log
      Runtime: python3.8
      Events:
        ExerciseLog:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exercise_log
            Method: get
  HoldingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
          AWS_ACCESS_KEY_ID: !Ref AWSAccessKeyId
          AWS_SECRET_ACCESS_KEY: !Ref AWSSecretAccessKey
          AWS_DEFAULT_REGION: !Ref AWSDefaultRegion
          DEV: !Ref Dev
      CodeUri: backend/
      Handler: home.get_holding
      Runtime: python3.8
      Events:
        Holding:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /holding
            Method: get
