name: Deploy API

on:
  # pull_request:
  #     branches: [master]
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # add step to define env var AWS_S3_BUCKET (>> $GITHUB_ENVdepending on github.ref
      # and then modify envkey_S3Bucket: ${{ env.AWS_S3_BUCKET }}

      - name: Create parameters.env
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_Dev: false
          envkey_S3Bucket: ${{ secrets.AWS_S3_BUCKET }}
          directory: src/api
          file_name: parameters.env

      - name: Build API
        run: npm run build:api

      - name: Deploy API
        run: npm run deploy:api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
