name: Deploy API

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Create parameters.env [prod]
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_S3Bucket: ${{ secrets.HYPERDRIVE_BUCKET }}
          envkey_Stage: prod
          envkey_ApiUrl: api.forcepu.sh
          envkey_CertArn: ${{ secrets.CERT_ARN }}
          envkey_HostedZoneId: ${{ secrets.HOSTED_ZONE_ID }}
          envkey_UserPoolArn: ${{ secrets.USER_POOL_ARN }}
          directory: src/api
          file_name: parameters.env
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Create parameters.env [dev]
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_S3Bucket: ${{ secrets.HYPERDRIVE_DEV_BUCKET }}
          envkey_Stage: dev
          envkey_ApiUrl: api.dev.forcepu.sh
          envkey_CertArn: ${{ secrets.DEV_CERT_ARN }}
          envkey_HostedZoneId: ${{ secrets.HOSTED_ZONE_ID }}
          envkey_UserPoolArn: ${{ secrets.DEV_USER_POOL_ARN }}
          directory: src/api
          file_name: dev-parameters.env
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Build API
        run: npm run build:api

      - name: Deploy API [prod]
        run: npm run deploy:api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy API [dev]
        run: npm run deploy-dev:api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ github.ref != 'refs/heads/master' }}
