name: Deploy API

on:
  pull_request:
    branches: [master]
  push:
    branches: [master, feature/notification]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up AWS SAM
        run: util/install_sam.sh || util/upgrade_sam.sh

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create parameters.env [prod]
        env:
          EmailUser: ${{ secrets.EMAIL_USER }}
          EmailPass: ${{ secrets.EMAIL_PASS }}
          StripePriceId: ${{ secrets.STRIPE_PRICE_ID }}
          StripeSecretKey: ${{ secrets.STRIPE_SECRET_KEY }}
          # Webhook signing key secret for endpoint (not for CLI)
          StripeWebhookSecret: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          S3Bucket: ${{ secrets.HYPERDRIVE_BUCKET }}
          Stage: prod
          ApiUrl: api.forcepu.sh
          CertArn: ${{ secrets.CERT_ARN }}
          HostedZoneId: ${{ secrets.HOSTED_ZONE_ID }}
          UserPoolArn: ${{ secrets.USER_POOL_ARN }}
          Salt: ${{ secrets.SALT }}
          CryptPass: ${{ secrets.CRYPT_PASS }}
          EmitSecret: ${{ secrets.EMIT_SECRET }}
        run: |
          echo "
          EmailUser=${EmailUser}
          EmailPass=${EmailPass}
          StripePriceId=${StripePriceId}
          StripeSecretKey=${StripeSecretKey}
          StripeWebhookSecret=${StripeWebhookSecret}
          S3Bucket=${S3Bucket}
          Stage=${Stage}
          ApiUrl=${ApiUrl}
          CertArn=${CertArn}
          HostedZoneId=${HostedZoneId}
          UserPoolArn=${UserPoolArn}
          Salt=${Salt}
          CryptPass=${CryptPass}
          EmitSecret=${EmitSecret}
          " >> src/api/parameters.env
        if: ${{ github.ref_name == 'master' }}

      - name: Create parameters.env [dev]
        env:
          EmailUser: ${{ secrets.DEV_EMAIL_USER }}
          EmailPass: ${{ secrets.EMAIL_PASS }}
          StripePriceId: ${{ secrets.DEV_STRIPE_PRICE_ID }}
          StripeSecretKey: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
          # Webhook signing key secret for endpoint (not for CLI)
          StripeWebhookSecret: ${{ secrets.DEV_STRIPE_WEBHOOK_SECRET }}
          S3Bucket: ${{ secrets.HYPERDRIVE_DEV_BUCKET }}
          Stage: dev
          ApiUrl: api.dev.forcepu.sh
          CertArn: ${{ secrets.DEV_CERT_ARN }}
          HostedZoneId: ${{ secrets.HOSTED_ZONE_ID }}
          UserPoolArn: ${{ secrets.DEV_USER_POOL_ARN }}
          Salt: ${{ secrets.SALT }}
          CryptPass: ${{ secrets.CRYPT_PASS }}
          EmitSecret: ${{ secrets.DEV_EMIT_SECRET }}
        run: |
          echo "
          EmailUser=${EmailUser}
          EmailPass=${EmailPass}
          StripePriceId=${StripePriceId}
          StripeSecretKey=${StripeSecretKey}
          StripeWebhookSecret=${StripeWebhookSecret}
          S3Bucket=${S3Bucket}
          Stage=${Stage}
          ApiUrl=${ApiUrl}
          CertArn=${CertArn}
          HostedZoneId=${HostedZoneId}
          UserPoolArn=${UserPoolArn}
          Salt=${Salt}
          CryptPass=${CryptPass}
          EmitSecret=${EmitSecret}
          " >> src/api/dev-parameters.env
        if: ${{ github.ref_name != 'master' }}

      - name: Build API
        run: npm run build:api

      - name: Deploy API [prod]
        run: npm run deploy:api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ github.ref_name == 'master' }}

      - name: Deploy API [dev]
        run: npm run deploy-dev:api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ github.ref_name != 'master' }}
