name: Deploy API

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up AWS SAM
        run: util/install_sam.sh || util/upgrade_sam.sh

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create parameters.env [prod]
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_STRIPESECRETKEY: ${{ secrets.STRIPE_SECRET_KEY }}
          envkey_S3BUCKET: ${{ secrets.HYPERDRIVE_BUCKET }}
          envkey_STAGE: prod
          envkey_APIURL: api.forcepu.sh
          envkey_CERTARN: ${{ secrets.CERT_ARN }}
          envkey_HOSTEDZONEID: ${{ secrets.HOSTED_ZONE_ID }}
          envkey_USERPOOLARN: ${{ secrets.USER_POOL_ARN }}
          directory: src/api
          file_name: parameters.env
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Create parameters.env [dev]
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_STRIPESECRETKEY: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
          envkey_S3BUCKET: ${{ secrets.HYPERDRIVE_DEV_BUCKET }}
          envkey_STAGE: dev
          envkey_APIURL: api.dev.forcepu.sh
          envkey_CERTARN: ${{ secrets.DEV_CERT_ARN }}
          envkey_HOSTEDZONEID: ${{ secrets.HOSTED_ZONE_ID }}
          envkey_USERPOOLARN: ${{ secrets.DEV_USER_POOL_ARN }}
          directory: src/api
          file_name: dev-parameters.env
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Build API
        run: npm run build:api

      - name: Deploy API [prod]
        run: npm run deploy:api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy API [dev]
        run: npm run deploy-dev:api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ github.ref != 'refs/heads/master' }}
