name: Hosted Zone

on:
  push:
    branches: [feature/research]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Get hosted zone
        env:
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        run: python -c "import os; print(os.environ['HOSTED_ZONE_ID'][-2:])"
