name: Deploy UmiJS

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm run ci

      - name: Create aws-exports.js file
        run: touch src/aws-exports.js

      - name: Build app [dev]
        run: npm run build-dev:umi && echo "AWS_S3_BUCKET=${AWS_S3_BUCKET}" >> $GITHUB_ENV && echo "CF_DISTRO_ID=${CF_DISTRO_ID}" >> $GITHUB_ENV
        env:
          AWS_S3_BUCKET: ${{ secrets.FORCEPUSH_DEV_BUCKET }}
          UMI_APP_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          UMI_APP_IDENTITY_POOL_ID: ${{ secrets.DEV_IDENTITY_POOL_ID }}
          UMI_APP_USER_POOL_ID: ${{ secrets.DEV_USER_POOL_ID }}
          UMI_APP_WEB_CLIENT_ID: ${{ secrets.DEV_WEB_CLIENT_ID }}
          UMI_APP_OAUTH_DOMAIN: ${{ secrets.DEV_OAUTH_DOMAIN }}
          CF_DISTRO_ID: ${{ secrets.DEV_CF_DISTRO_ID }}
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Build app [prod]
        run: npm run build:umi && echo "AWS_S3_BUCKET=${AWS_S3_BUCKET}" >> $GITHUB_ENV && echo "CF_DISTRO_ID=${CF_DISTRO_ID}" >> $GITHUB_ENV
        env:
          AWS_S3_BUCKET: ${{ secrets.FORCEPUSH_BUCKET }}
          UMI_APP_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          UMI_APP_IDENTITY_POOL_ID: ${{ secrets.IDENTITY_POOL_ID }}
          UMI_APP_USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          UMI_APP_WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}
          UMI_APP_OAUTH_DOMAIN: ${{ secrets.OAUTH_DOMAIN }}
          CF_DISTRO_ID: ${{ secrets.CF_DISTRO_ID }}
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy umi
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "dist"

      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id "${CF_DISTRO_ID}" --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
