name: Deploy UmiJS

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm run ci

      - name: Configure Amplify [dev]
        # run: APP_ID="${APP_ID}" ENV="dev" npm run amplify
        run: APP_ID="${APP_ID}" ENV="dev" npm run amp
        env:
          APP_ID: ${{ secrets.APP_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Configure Amplify [prod]
        # run: APP_ID="${APP_ID}" ENV="prod" npm run amplify
        run: APP_ID="${APP_ID}" ENV="prod" npm run amp
        env:
          APP_ID: ${{ secrets.APP_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Build app [dev]
        run: npm run build-dev:umi && echo "AWS_S3_BUCKET=${AWS_S3_BUCKET}" >> $GITHUB_ENV
        env:
          AWS_S3_BUCKET: ${{ secrets.FORCEPUSH_DEV_BUCKET }}
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Build app [prod]
        run: npm run build:umi && echo "AWS_S3_BUCKET=${AWS_S3_BUCKET}" >> $GITHUB_ENV
        env:
          AWS_S3_BUCKET: ${{ secrets.FORCEPUSH_BUCKET }}
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy umi
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "dist"
